const storageKey = "zhijian-articles";
const favoritesKey = "zhijian-favorites";
const foldersKey = "zhijian-favorite-folders";
const isLocalAdmin = location.hostname === "localhost" || location.hostname === "127.0.0.1" || location.protocol === "file:";
let articles = window.loadArticles(storageKey);
let activeId = articles[0]?.id;
let editingId = null;
const list = document.querySelector("#articleList"), count = document.querySelector("#articleCount");
let favorites = window.loadBlogCollection(favoritesKey), folders = window.loadBlogCollection(foldersKey, ["默认收藏"]);
let activeFolder = folders[0], activeFavoriteType = null;
if (!isLocalAdmin) document.querySelectorAll(".admin-only").forEach(element => element.hidden = true);
const escapeHtml = (value) => value.replace(/[&<>\"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[char]));
const contentKey = value => { let hash = 5381; for (const char of value) hash = (hash * 33) ^ char.charCodeAt(0); return `saved-${hash >>> 0}`; };
function inlineMarkup(text) { return escapeHtml(text).replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>"); }
function markup(text) { return text.split("\n").map(line => { if (line.startsWith("## ")) return `<h3>${inlineMarkup(line.slice(3))}</h3>`; if (line.startsWith("> ")) return `<blockquote>${inlineMarkup(line.slice(2))}</blockquote>`; if (!line.trim()) return ""; return `<p>${inlineMarkup(line)}</p>`; }).join(""); }
function dateLabel(date) { return new Intl.DateTimeFormat("zh-CN", { year:"numeric", month:"long", day:"numeric" }).format(new Date(`${date}T00:00:00`)); }
function persist() { localStorage.setItem(storageKey, JSON.stringify(articles)); }
function persistRepositoryData() { fetch("/api/local-data", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ articles, favorites, folders, notes:JSON.parse(localStorage.getItem("zhijian-reader-notes") || "[]") }) }).catch(() => {}); }
function render() { count.textContent = String(articles.length).padStart(2,"0"); list.innerHTML = articles.length ? articles.map(article => `<a class="article-item" href="article.html?id=${encodeURIComponent(article.id)}"><time>${article.date.replaceAll("-", ".")}</time><h3>${escapeHtml(article.title)}</h3><span class="read-arrow">↗</span></a>`).join("") : `<p class="empty-list">还没有文章。<br />从右上角写下第一篇吧。</p>`; }
const dialog = document.querySelector("#composer"), form = document.querySelector("#articleForm");
const field = id => document.querySelector(id);
function setComposerMode(article) { editingId = article?.id || null; field("#composerKicker").textContent = article ? "EDIT ENTRY" : "NEW ENTRY"; field("#composerTitle").textContent = article ? "修改这篇文章" : "写下这一刻"; field("#submitArticle").textContent = article ? "保存修改" : "发布文章"; }
function open(article) { form.reset(); setComposerMode(article); field("#fileName").textContent = "支持 .md / .txt"; field("#chartBuilder").hidden = true; if (article) { field("#titleInput").value = article.title; field("#dateInput").value = article.date; field("#categoryInput").value = article.category; field("#excerptInput").value = article.excerpt; field("#contentInput").value = article.content; } else { field("#dateInput").value = new Date().toISOString().slice(0,10); } dialog.showModal(); }
function closeComposer() { dialog.close(); editingId = null; }
document.querySelector("#openComposer").addEventListener("click", () => open()); ["#closeComposer", "#cancelComposer"].forEach(id => document.querySelector(id).addEventListener("click", closeComposer));
document.querySelector("#importButton").addEventListener("click", () => document.querySelector("#fileInput").click());
document.querySelector("#fileInput").addEventListener("change", async event => { const file = event.target.files[0]; if (!file) return; document.querySelector("#contentInput").value = await file.text(); document.querySelector("#fileName").textContent = file.name; });
document.querySelector("#imageButton").addEventListener("click", () => field("#imageInput").click());
field("#imageInput").addEventListener("change", async event => { const image = event.target.files[0]; if (!image) return; const dataUrl = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(image); }); field("#contentInput").value += `${field("#contentInput").value.trim() ? "\n\n" : ""}![${image.name}](${dataUrl})`; field("#fileName").textContent = `已插入图片：${image.name}`; });
field("#chartButton").addEventListener("click", () => { field("#chartBuilder").hidden = !field("#chartBuilder").hidden; });
function chartImage(title, labels, values) { const canvas = document.createElement("canvas"), width = 900, height = 520, pad = { top:78, right:54, bottom:86, left:65 }; canvas.width = width; canvas.height = height; const ctx = canvas.getContext("2d"), max = Math.max(...values, 1), chartHeight = height - pad.top - pad.bottom, chartWidth = width - pad.left - pad.right; ctx.fillStyle = "#fbfcf9"; ctx.fillRect(0,0,width,height); ctx.fillStyle = "#18231e"; ctx.font = "600 25px sans-serif"; ctx.fillText(title, pad.left, 43); ctx.strokeStyle = "#d9ddd6"; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(pad.left, height - pad.bottom); ctx.lineTo(width - pad.right, height - pad.bottom); ctx.stroke(); const gap = chartWidth / labels.length, barWidth = Math.min(76, gap * .58); values.forEach((value, index) => { const barHeight = Math.max(12, value / max * chartHeight), x = pad.left + gap * index + (gap - barWidth) / 2, y = height - pad.bottom - barHeight; ctx.fillStyle = "#bdd74e"; ctx.beginPath(); ctx.roundRect(x, y, barWidth, barHeight, 12); ctx.fill(); ctx.fillStyle = "#526057"; ctx.font = "500 18px monospace"; ctx.textAlign = "center"; ctx.fillText(String(value), x + barWidth / 2, y - 12); ctx.font = "500 16px sans-serif"; ctx.fillText(labels[index], x + barWidth / 2, height - pad.bottom + 32); }); return canvas.toDataURL("image/png"); }
field("#insertChart").addEventListener("click", () => { const title = field("#chartTitle").value.trim() || "数据记录"; const labels = field("#chartLabels").value.split(",").map(item => item.trim()).filter(Boolean); const values = field("#chartValues").value.split(",").map(item => Number(item.trim())); if (!labels.length || labels.length !== values.length || values.some(value => !Number.isFinite(value))) { alert("请填写数量一致的标签和数值。"); return; } field("#contentInput").value += `${field("#contentInput").value.trim() ? "\n\n" : ""}![${title}]( ${chartImage(title, labels, values)} )`.replace("( ", "(").replace(" )", ")"); field("#chartBuilder").hidden = true; field("#chartTitle").value = ""; field("#chartLabels").value = ""; field("#chartValues").value = ""; });
form.addEventListener("submit", event => { event.preventDefault(); const article = { id: editingId || `${Date.now()}`, title: field("#titleInput").value.trim(), date: field("#dateInput").value, category: field("#categoryInput").value.trim(), excerpt: field("#excerptInput").value.trim(), content: field("#contentInput").value.trim() }; const existingIndex = articles.findIndex(item => item.id === editingId); if (existingIndex >= 0) articles[existingIndex] = article; else articles.unshift(article); persist(); persistRepositoryData(); activeId = article.id; closeComposer(); render(); });
const editTarget = new URLSearchParams(location.search).get("edit");
if (editTarget) { const article = articles.find(item => item.id === editTarget); if (article) open(article); history.replaceState({}, "", "index.html"); }
const favoritesDialog = field("#favoritesDialog");
function persistFavorites() { localStorage.setItem(favoritesKey, JSON.stringify(favorites)); localStorage.setItem(foldersKey, JSON.stringify(folders)); persistRepositoryData(); }
function renderFavorites() { const labels = {article:"文章",text:"文字",image:"图片",chart:"图表"}; const entries = favorites.filter(item => item.folder === activeFolder); field("#folderPills").innerHTML = folders.map(folder => `<button class="folder-pill ${folder === activeFolder ? "active" : ""}" data-folder-name="${escapeHtml(folder)}" type="button">${escapeHtml(folder)}</button>`).join(""); const tabs = Object.entries(labels).map(([type, label]) => `<button class="favorite-tab ${activeFavoriteType === type ? "active" : ""}" data-favorite-type="${type}" type="button">${label}<span>${entries.filter(item => item.type === type).length}</span></button>`).join(""); const selected = activeFavoriteType ? entries.filter(item => item.type === activeFavoriteType) : []; field("#favoritesList").innerHTML = `<section class="folder-section"><h3>${escapeHtml(activeFolder)}</h3><div class="favorite-tabs">${tabs}</div>${activeFavoriteType ? `<div class="favorite-detail">${selected.length ? selected.map(item => { const target = item.type === "article" ? "article" : contentKey(item.content); return `<article class="favorite-card"><a class="favorite-card-link" href="article.html?id=${encodeURIComponent(item.articleId)}&target=${encodeURIComponent(target)}"><h3>${escapeHtml(item.title)}</h3></a><button class="remove-favorite" data-favorite-id="${item.id}" type="button" aria-label="移除收藏">×</button></article>`; }).join("") : `<p class="empty-group">暂无${labels[activeFavoriteType]}</p>`}</div>` : `<p class="empty-group">选择上方类别查看收藏内容。</p>`}</section>`; }
field("#openFavorites").addEventListener("click", () => { renderFavorites(); favoritesDialog.showModal(); });
field("#closeFavorites").addEventListener("click", () => favoritesDialog.close());
field("#folderForm").addEventListener("submit", event => { event.preventDefault(); const name = field("#folderInput").value.trim(); if (!name || folders.includes(name)) return; folders.push(name); field("#folderInput").value = ""; persistFavorites(); renderFavorites(); });
field("#folderPills").addEventListener("click", event => { const button = event.target.closest("[data-folder-name]"); if (!button) return; activeFolder = button.dataset.folderName; activeFavoriteType = null; renderFavorites(); });
field("#favoritesList").addEventListener("click", event => { const tab = event.target.closest("[data-favorite-type]"); if (tab) { activeFavoriteType = tab.dataset.favoriteType; renderFavorites(); return; } const button = event.target.closest("[data-favorite-id]"); if (!button) return; favorites = favorites.filter(item => item.id !== button.dataset.favoriteId); persistFavorites(); renderFavorites(); });
render();
