(() => {
  let user = null;
  let data = { favorites: [], folders: ["默认收藏"], notes: [] };
  let useServer = location.protocol !== "file:";
  const clone = value => JSON.parse(JSON.stringify(value));
  const normalize = value => ({ favorites:Array.isArray(value?.favorites) ? value.favorites : [], folders:Array.isArray(value?.folders) && value.folders.length ? value.folders : ["默认收藏"], notes:Array.isArray(value?.notes) ? value.notes : [] });
  const localKey = id => `zhijian-user-data-${id}`;
  const localRead = id => { try { return normalize(JSON.parse(localStorage.getItem(localKey(id)) || "null")); } catch { return normalize(null); } };
  const request = async (url, options = {}) => { const response = await fetch(url, options); const payload = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.error || "请求失败"); return payload; };
  const loadData = async id => { if (useServer) try { return normalize(await request(`/api/user-data?id=${encodeURIComponent(id)}`)); } catch { useServer = false; } return localRead(id); };
  const dialog = document.createElement("dialog");
  dialog.id = "loginDialog";
  dialog.innerHTML = `<form class="login-card" id="loginForm"><div class="composer-head"><div><p class="eyebrow">WELCOME BACK</p><h2>进入纸间</h2></div><button class="icon-button" id="closeLogin" type="button" aria-label="关闭">×</button></div><label>账号 ID<input id="loginId" autocomplete="username" required placeholder="输入用户ID" /></label><p class="login-error" id="loginError" role="alert"></p><button class="save-button" type="submit">进入</button></form>`;
  document.body.append(dialog);
  const actions = document.querySelector(".topbar-actions") || document.querySelector(".topbar");
  const account = document.createElement("div");
  account.className = "account-controls";
  actions.append(account);
  const broadcast = () => document.dispatchEvent(new CustomEvent("userchange", { detail:{ user, data:clone(data) } }));
  const renderAccount = () => { account.innerHTML = user ? `<span class="account-label">${user.id}${user.role === "admin" ? " · 管理员" : ""}</span><button class="auth-button" id="logoutButton" type="button">退出</button>` : `<button class="auth-button" id="loginButton" type="button">登录</button>`; account.querySelector("#loginButton")?.addEventListener("click", () => dialog.showModal()); account.querySelector("#logoutButton")?.addEventListener("click", () => { localStorage.removeItem("zhijian-active-id"); user = null; data = normalize(null); renderAccount(); broadcast(); }); };
  const idInput = dialog.querySelector("#loginId");
  dialog.querySelector("#closeLogin").addEventListener("click", () => dialog.close());
  dialog.querySelector("#loginForm").addEventListener("submit", async event => { event.preventDefault(); const id = idInput.value.trim(); if (!id) return; user = { id, role:id === "admin" ? "admin" : "user" }; data = await loadData(id); localStorage.setItem("zhijian-active-id", id); dialog.close(); renderAccount(); broadcast(); });
  const ready = (async () => { const id = localStorage.getItem("zhijian-active-id"); if (id) { user = { id, role:id === "admin" ? "admin" : "user" }; data = await loadData(id); } renderAccount(); return { user, data:clone(data) }; })();
  window.userStore = { get user() { return user; }, get data() { return clone(data); }, ready, requireLogin() { if (user) return true; dialog.showModal(); return false; }, async saveUserData(next) { if (!user) throw new Error("请先登录"); data = normalize(next); localStorage.setItem(localKey(user.id), JSON.stringify(data)); if (useServer) try { await request(`/api/user-data?id=${encodeURIComponent(user.id)}`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(data) }); } catch { useServer = false; } broadcast(); } };
})();
