const notesKey = "zhijian-reader-notes";
let notes = JSON.parse(localStorage.getItem(notesKey) || "[]");
let selectedNoteId = null;
const $ = selector => document.querySelector(selector);
const esc = value => value.replace(/[&<>\"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[char]));
function renderNotes() { $("#notesCount").textContent = String(notes.length).padStart(2, "0"); $("#notesList").innerHTML = notes.length ? notes.slice().reverse().map(note => `<button class="note-card" data-note-id="${note.id}" type="button"><time>${note.date}</time><h2>${esc(note.title)}</h2><p>${esc(note.content)}</p><span>点击阅读 →</span></button>`).join("") : `<p class="empty-favorites">还没有随笔。点击上方“写随笔”开始记录。</p>`; }
$("#notesList").addEventListener("click", event => { const card = event.target.closest("[data-note-id]"); if (!card) return; const note = notes.find(item => item.id === card.dataset.noteId); if (!note) return; selectedNoteId = note.id; $("#viewerDate").textContent = note.date; $("#viewerTitle").textContent = note.title; $("#viewerContent").innerHTML = esc(note.content).split("\n").map(line => line ? `<p>${line}</p>` : "").join(""); $("#editNote").href = `note-editor.html?edit=${encodeURIComponent(note.id)}`; $("#noteViewer").showModal(); });
$("#closeNoteViewer").addEventListener("click", () => $("#noteViewer").close());
$("#deleteNote").addEventListener("click", () => { const note = notes.find(item => item.id === selectedNoteId); if (!note || !confirm(`确定删除《${note.title}》吗？`)) return; notes = notes.filter(item => item.id !== selectedNoteId); localStorage.setItem(notesKey, JSON.stringify(notes)); fetch("/api/local-data", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ articles:JSON.parse(localStorage.getItem("zhijian-articles") || "[]"), favorites:JSON.parse(localStorage.getItem("zhijian-favorites") || "[]"), folders:JSON.parse(localStorage.getItem("zhijian-favorite-folders") || "[\"默认收藏\"]"), notes }) }).catch(() => {}); $("#noteViewer").close(); renderNotes(); });
renderNotes();
