const $ = selector => document.querySelector(selector);
const esc = value => value.replace(/[&<>\"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[char]));
const editingId = new URLSearchParams(location.search).get("edit");
let notes = [];
let favorites = [];
const contentKey = value => { let hash = 5381; for (const char of value) hash = (hash * 33) ^ char.charCodeAt(0); return `saved-${hash >>> 0}`; };
const favoriteText = item => item.type === "article" ? (() => { const article = window.loadArticles("zhijian-articles").find(entry => entry.id === item.content); return article ? `${article.title}\n${article.excerpt}` : item.title; })() : item.content.replace(/^\{\{chart\|/, "图表：").replace(/\}\}$/, "");
const originalLink = item => `[查看原文](article.html?id=${encodeURIComponent(item.articleId)}&target=${encodeURIComponent(item.type === "article" ? "article" : contentKey(item.content))})`;
function renderReferences() { $("#referenceList").innerHTML = favorites.length ? favorites.slice().reverse().map(item => `<button class="reference-item" data-reference-id="${item.id}" type="button"><span>${esc(item.folder)} · ${esc(item.type)}</span><strong>${esc(item.title)}</strong></button>`).join("") : `<p class="empty-favorites">收藏夹还是空的。</p>`; }
function hydrate(data) { notes = data.notes; favorites = data.favorites; const existing = editingId ? notes.find(note => note.id === editingId) : null; if (existing) { $("#noteKicker").textContent = "EDIT A NOTE"; $("#noteHeading").textContent = "修改随笔"; $("#noteTitle").value = existing.title; $("#noteContent").value = existing.content; $("#saveNote").textContent = "保存修改"; } }
$("#openReferences").addEventListener("click", () => { if (!window.userStore.requireLogin()) return; renderReferences(); $("#referencesDialog").showModal(); });
$("#closeReferences").addEventListener("click", () => $("#referencesDialog").close());
$("#referenceList").addEventListener("click", event => { const item = event.target.closest("[data-reference-id]"); if (!item) return; const favorite = favorites.find(entry => entry.id === item.dataset.referenceId); if (!favorite) return; $("#noteContent").value += `${$("#noteContent").value.trim() ? "\n\n" : ""}> ${favoriteText(favorite).replace(/\n/g, "\n> ")}\n${originalLink(favorite)}`; $("#referencesDialog").close(); });
$("#saveNote").addEventListener("click", async () => { if (!window.userStore.requireLogin()) return; const title = $("#noteTitle").value.trim(), content = $("#noteContent").value.trim(); if (!title || !content) return; const existing = notes.find(note => note.id === editingId); const note = { id:editingId || `${Date.now()}`, title, content, date:existing?.date || new Intl.DateTimeFormat("zh-CN", { year:"numeric", month:"2-digit", day:"2-digit" }).format(new Date()) }; const index = notes.findIndex(item => item.id === editingId); if (index >= 0) notes[index] = note; else notes.push(note); await window.userStore.saveUserData({ favorites, folders:window.userStore.data.folders, notes }); location.href = "notes.html"; });
window.userStore.ready.then(({ user, data }) => { if (!user) { window.userStore.requireLogin(); return; } hydrate(data); });
