const $ = selector => document.querySelector(selector);
const esc = value => value.replace(/[&<>\"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[char]));
const editingId = new URLSearchParams(location.search).get("edit");
let notes = [];
let favorites = [];
let folders = ["默认收藏"];
let activeReferenceFolder = "默认收藏";
let activeReferenceType = null;
const referenceLabels = { article:"文章", heading:"板块" };
const contentKey = value => { let hash = 5381; for (const char of value) hash = (hash * 33) ^ char.charCodeAt(0); return `saved-${hash >>> 0}`; };
const favoriteText = item => item.type === "article" ? (() => { const article = window.loadArticles("zhijian-articles").find(entry => entry.id === item.content); return article ? `${article.title}\n${article.excerpt}` : item.title; })() : item.content;
const originalLink = item => `[查看原文](article.html?id=${encodeURIComponent(item.articleId)}&target=${encodeURIComponent(item.type === "article" ? "article" : contentKey(item.content))})`;
function renderReferences() { if (!folders.includes(activeReferenceFolder)) activeReferenceFolder = folders[0] || "默认收藏"; const entries = favorites.filter(item => item.folder === activeReferenceFolder && referenceLabels[item.type]); const folderPills = folders.map(folder => `<button class="folder-pill ${folder === activeReferenceFolder ? "active" : ""}" data-reference-folder="${esc(folder)}" type="button">${esc(folder)}</button>`).join(""); const tabs = Object.entries(referenceLabels).map(([type, label]) => `<button class="favorite-tab ${activeReferenceType === type ? "active" : ""}" data-reference-type="${type}" type="button">${label}<span>${entries.filter(item => item.type === type).length}</span></button>`).join(""); const selected = activeReferenceType ? entries.filter(item => item.type === activeReferenceType) : []; $("#referenceList").innerHTML = `<div class="reference-browser"><div class="folder-pills">${folderPills}</div><div class="favorite-tabs">${tabs}</div>${activeReferenceType ? `<div class="reference-list">${selected.length ? selected.map(item => `<button class="reference-item" data-reference-id="${item.id}" type="button"><span>${esc(item.folder)} · ${referenceLabels[item.type]}</span><strong>${esc(item.title)}</strong></button>`).join("") : `<p class="empty-group">暂无${referenceLabels[activeReferenceType]}</p>`}</div>` : `<p class="empty-group">选择上方类别查看收藏内容。</p>`}</div>`; }
function hydrate(data) { notes = data.notes; favorites = data.favorites.filter(item => referenceLabels[item.type]); folders = data.folders.length ? data.folders : ["默认收藏"]; activeReferenceFolder = folders[0]; const existing = editingId ? notes.find(note => note.id === editingId) : null; if (existing) { $("#noteKicker").textContent = "EDIT A NOTE"; $("#noteHeading").textContent = "修改随笔"; $("#noteTitle").value = existing.title; $("#noteContent").value = existing.content; $("#saveNote").textContent = "保存修改"; } }
$("#openReferences").addEventListener("click", () => { if (!window.userStore.requireLogin()) return; renderReferences(); $("#referencesDialog").showModal(); });
$("#closeReferences").addEventListener("click", () => $("#referencesDialog").close());
$("#referenceList").addEventListener("click", event => { const folder = event.target.closest("[data-reference-folder]"); if (folder) { activeReferenceFolder = folder.dataset.referenceFolder; activeReferenceType = null; renderReferences(); return; } const tab = event.target.closest("[data-reference-type]"); if (tab) { activeReferenceType = tab.dataset.referenceType; renderReferences(); return; } const item = event.target.closest("[data-reference-id]"); if (!item) return; const favorite = favorites.find(entry => entry.id === item.dataset.referenceId); if (!favorite) return; $("#noteContent").value += `${$("#noteContent").value.trim() ? "\n\n" : ""}> ${favoriteText(favorite).replace(/\n/g, "\n> ")}\n${originalLink(favorite)}`; $("#referencesDialog").close(); });
$("#saveNote").addEventListener("click", async () => { if (!window.userStore.requireLogin()) return; const title = $("#noteTitle").value.trim(), content = $("#noteContent").value.trim(); if (!title || !content) return; const existing = notes.find(note => note.id === editingId); const note = { id:editingId || `${Date.now()}`, title, content, date:existing?.date || new Intl.DateTimeFormat("zh-CN", { year:"numeric", month:"2-digit", day:"2-digit" }).format(new Date()) }; const index = notes.findIndex(item => item.id === editingId); if (index >= 0) notes[index] = note; else notes.push(note); await window.userStore.saveUserData({ favorites, folders:window.userStore.data.folders, notes }); location.href = "notes.html"; });
window.userStore.ready.then(({ user, data }) => { if (!user) { window.userStore.requireLogin(); return; } hydrate(data); });
